<?php
/**
 * BatteriesInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  namespace Fulfillment\StraightShip\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Techship API v3
 *
 * API regions:  US: <a href='https://api-us.techship.io/api/docs/ui/index'>https://api-us.techship.io/api/docs/ui/index</a>  CA: <a href='https://api-ca.techship.io/api/docs/ui/index'>https://api-ca.techship.io/api/docs/ui/index</a>
 *
 * OpenAPI spec version: V3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.61
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Fulfillment\StraightShip\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BatteriesInfoTest Class Doc Comment
 *
 * @category    Class
 * @description BatteriesInfo
 * @package     namespace Fulfillment\StraightShip\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BatteriesInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BatteriesInfo"
     */
    public function testBatteriesInfo()
    {
    }

    /**
     * Test attribute "batteries"
     */
    public function testPropertyBatteries()
    {
    }

    /**
     * Test attribute "battery_packing_type"
     */
    public function testPropertyBatteryPackingType()
    {
    }

    /**
     * Test attribute "battery_material_type"
     */
    public function testPropertyBatteryMaterialType()
    {
    }

    /**
     * Test attribute "battery_regulatory_sub_type"
     */
    public function testPropertyBatteryRegulatorySubType()
    {
    }
}
