<?php
/**
 * CustomsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  namespace Fulfillment\StraightShip\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Techship API v3
 *
 * API regions:  US: <a href='https://api-us.techship.io/api/docs/ui/index'>https://api-us.techship.io/api/docs/ui/index</a>  CA: <a href='https://api-ca.techship.io/api/docs/ui/index'>https://api-ca.techship.io/api/docs/ui/index</a>
 *
 * OpenAPI spec version: V3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.61
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Fulfillment\StraightShip\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CustomsTest Class Doc Comment
 *
 * @category    Class
 * @description Customs information (for commercial invoice)
 * @package     namespace Fulfillment\StraightShip\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Customs"
     */
    public function testCustoms()
    {
    }

    /**
     * Test attribute "terms_of_trade"
     */
    public function testPropertyTermsOfTrade()
    {
    }

    /**
     * Test attribute "place_of_incoterm"
     */
    public function testPropertyPlaceOfIncoterm()
    {
    }

    /**
     * Test attribute "itn_number"
     */
    public function testPropertyItnNumber()
    {
    }

    /**
     * Test attribute "duty_billing"
     */
    public function testPropertyDutyBilling()
    {
    }

    /**
     * Test attribute "sender_tax"
     */
    public function testPropertySenderTax()
    {
    }

    /**
     * Test attribute "sender_tax_info"
     */
    public function testPropertySenderTaxInfo()
    {
    }

    /**
     * Test attribute "receiver_tax_info"
     */
    public function testPropertyReceiverTaxInfo()
    {
    }

    /**
     * Test attribute "exporter_tax_info"
     */
    public function testPropertyExporterTaxInfo()
    {
    }

    /**
     * Test attribute "importer_tax_info"
     */
    public function testPropertyImporterTaxInfo()
    {
    }

    /**
     * Test attribute "commercial_invoice_declaration_statement"
     */
    public function testPropertyCommercialInvoiceDeclarationStatement()
    {
    }

    /**
     * Test attribute "commercial_invoice_special_instructions"
     */
    public function testPropertyCommercialInvoiceSpecialInstructions()
    {
    }
}
