<?php
/**
 * InputPackageItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  namespace Fulfillment\StraightShip\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Techship API v3
 *
 * API regions:  US: <a href='https://api-us.techship.io/api/docs/ui/index'>https://api-us.techship.io/api/docs/ui/index</a>  CA: <a href='https://api-ca.techship.io/api/docs/ui/index'>https://api-ca.techship.io/api/docs/ui/index</a>
 *
 * OpenAPI spec version: V3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.61
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Fulfillment\StraightShip\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * InputPackageItemTest Class Doc Comment
 *
 * @category    Class
 * @description InputPackageItem
 * @package     namespace Fulfillment\StraightShip\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InputPackageItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InputPackageItem"
     */
    public function testInputPackageItem()
    {
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }

    /**
     * Test attribute "lot_number"
     */
    public function testPropertyLotNumber()
    {
    }

    /**
     * Test attribute "serial_number"
     */
    public function testPropertySerialNumber()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "description2"
     */
    public function testPropertyDescription2()
    {
    }

    /**
     * Test attribute "description3"
     */
    public function testPropertyDescription3()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "unit_weight"
     */
    public function testPropertyUnitWeight()
    {
    }

    /**
     * Test attribute "net_unit_weight"
     */
    public function testPropertyNetUnitWeight()
    {
    }

    /**
     * Test attribute "expiration_date"
     */
    public function testPropertyExpirationDate()
    {
    }

    /**
     * Test attribute "uom"
     */
    public function testPropertyUom()
    {
    }

    /**
     * Test attribute "supplier"
     */
    public function testPropertySupplier()
    {
    }

    /**
     * Test attribute "country_of_origin"
     */
    public function testPropertyCountryOfOrigin()
    {
    }

    /**
     * Test attribute "harmonized_code"
     */
    public function testPropertyHarmonizedCode()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "dangerous_goods"
     */
    public function testPropertyDangerousGoods()
    {
    }
}
