<?php
/**
 * PackageFreightChargeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  namespace Fulfillment\StraightShip\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Techship API v3
 *
 * API regions:  US: <a href='https://api-us.techship.io/api/docs/ui/index'>https://api-us.techship.io/api/docs/ui/index</a>  CA: <a href='https://api-ca.techship.io/api/docs/ui/index'>https://api-ca.techship.io/api/docs/ui/index</a>
 *
 * OpenAPI spec version: V3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.61
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Fulfillment\StraightShip\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PackageFreightChargeTest Class Doc Comment
 *
 * @category    Class
 * @description PackageFreightCharge
 * @package     namespace Fulfillment\StraightShip\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PackageFreightChargeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PackageFreightCharge"
     */
    public function testPackageFreightCharge()
    {
    }

    /**
     * Test attribute "tax1_type"
     */
    public function testPropertyTax1Type()
    {
    }

    /**
     * Test attribute "tax1_amount"
     */
    public function testPropertyTax1Amount()
    {
    }

    /**
     * Test attribute "tax2_type"
     */
    public function testPropertyTax2Type()
    {
    }

    /**
     * Test attribute "tax2_amount"
     */
    public function testPropertyTax2Amount()
    {
    }

    /**
     * Test attribute "tax3_type"
     */
    public function testPropertyTax3Type()
    {
    }

    /**
     * Test attribute "tax3_amount"
     */
    public function testPropertyTax3Amount()
    {
    }

    /**
     * Test attribute "shipping_charge"
     */
    public function testPropertyShippingCharge()
    {
    }

    /**
     * Test attribute "shipping_charge_total"
     */
    public function testPropertyShippingChargeTotal()
    {
    }

    /**
     * Test attribute "fuel_surcharge"
     */
    public function testPropertyFuelSurcharge()
    {
    }

    /**
     * Test attribute "fee_markup"
     */
    public function testPropertyFeeMarkup()
    {
    }

    /**
     * Test attribute "billable_weight"
     */
    public function testPropertyBillableWeight()
    {
    }

    /**
     * Test attribute "billable_weight_uom"
     */
    public function testPropertyBillableWeightUom()
    {
    }

    /**
     * Test attribute "dimensional_weight"
     */
    public function testPropertyDimensionalWeight()
    {
    }

    /**
     * Test attribute "dimensional_weight_uom"
     */
    public function testPropertyDimensionalWeightUom()
    {
    }
}
