<?php
/**
 * ShippingOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  namespace Fulfillment\StraightShip\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Techship API v3
 *
 * API regions:  US: <a href='https://api-us.techship.io/api/docs/ui/index'>https://api-us.techship.io/api/docs/ui/index</a>  CA: <a href='https://api-ca.techship.io/api/docs/ui/index'>https://api-ca.techship.io/api/docs/ui/index</a>
 *
 * OpenAPI spec version: V3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.61
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Fulfillment\StraightShip\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ShippingOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description ShippingOptions
 * @package     namespace Fulfillment\StraightShip\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingOptionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShippingOptions"
     */
    public function testShippingOptions()
    {
    }

    /**
     * Test attribute "signature_required"
     */
    public function testPropertySignatureRequired()
    {
    }

    /**
     * Test attribute "signature_adult"
     */
    public function testPropertySignatureAdult()
    {
    }

    /**
     * Test attribute "signature_indirect"
     */
    public function testPropertySignatureIndirect()
    {
    }

    /**
     * Test attribute "saturday_pickup"
     */
    public function testPropertySaturdayPickup()
    {
    }

    /**
     * Test attribute "saturday_delivery"
     */
    public function testPropertySaturdayDelivery()
    {
    }

    /**
     * Test attribute "proof_of_age18"
     */
    public function testPropertyProofOfAge18()
    {
    }

    /**
     * Test attribute "proof_of_age19"
     */
    public function testPropertyProofOfAge19()
    {
    }

    /**
     * Test attribute "hold_at_location"
     */
    public function testPropertyHoldAtLocation()
    {
    }

    /**
     * Test attribute "appointment_delivery"
     */
    public function testPropertyAppointmentDelivery()
    {
    }

    /**
     * Test attribute "dry_ice"
     */
    public function testPropertyDryIce()
    {
    }

    /**
     * Test attribute "special_handling"
     */
    public function testPropertySpecialHandling()
    {
    }

    /**
     * Test attribute "post_office_id"
     */
    public function testPropertyPostOfficeId()
    {
    }

    /**
     * Test attribute "hold_for_pickup_indicator"
     */
    public function testPropertyHoldForPickupIndicator()
    {
    }

    /**
     * Test attribute "dangerous_goods"
     */
    public function testPropertyDangerousGoods()
    {
    }

    /**
     * Test attribute "explosive"
     */
    public function testPropertyExplosive()
    {
    }

    /**
     * Test attribute "alcohol"
     */
    public function testPropertyAlcohol()
    {
    }

    /**
     * Test attribute "is_no_rts"
     */
    public function testPropertyIsNoRts()
    {
    }

    /**
     * Test attribute "perishable"
     */
    public function testPropertyPerishable()
    {
    }

    /**
     * Test attribute "keep_frozen"
     */
    public function testPropertyKeepFrozen()
    {
    }

    /**
     * Test attribute "two_persons"
     */
    public function testPropertyTwoPersons()
    {
    }

    /**
     * Test attribute "controlled_substance"
     */
    public function testPropertyControlledSubstance()
    {
    }

    /**
     * Test attribute "delivery_options"
     */
    public function testPropertyDeliveryOptions()
    {
    }

    /**
     * Test attribute "origin_signature_not_required"
     */
    public function testPropertyOriginSignatureNotRequired()
    {
    }

    /**
     * Test attribute "lift_gate_for_pick_up_indicator"
     */
    public function testPropertyLiftGateForPickUpIndicator()
    {
    }

    /**
     * Test attribute "lift_gate_for_delivery_indicator"
     */
    public function testPropertyLiftGateForDeliveryIndicator()
    {
    }

    /**
     * Test attribute "request_pickup"
     */
    public function testPropertyRequestPickup()
    {
    }
}
